# Generated by Django 3.0.3 on 2021-02-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrition',
            new_name='description',
        ),
    ]
